### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by vensanmazmanyan** [sofacoustics/SOFAlizer-for-Unity#1]
Dear developers,

first of all, thank you for your work and for the great tool you are developing.

I have successfully tested the previous version of SOFAlizer-for-Unity and was very eager to test the new release.
Unfortunatelly i couldn't get this to work.

When running the scene in Unity an error message appears.
Please, see this screenshot:

![crash_sofalizer4unity](https://user-images.githubusercontent.com/30050234/28026743-4cf06392-6597-11e7-9d93-d7e11686bc39.PNG)

I am running Windows 10 Pro on Intel i7-6950X with 128GB RAM and GTX 1080.

I really hope, you could provide a solution, because i would like to use the SOFAlizer for some experiments.

Best regards,
Vensan

**Comment by petibub** [comment]
How have you compiled the DLL?

**Comment by vensanmazmanyan** [comment]
I have used Visual Studio Community 2017 using following configuration:

![capture](https://user-images.githubusercontent.com/30050234/28027456-6875c95c-6599-11e7-9bdb-66c3eca1f7ce.PNG)

I have downloaded the latest libmysofa from:
https://github.com/hoene/libmysofa

The folders "SOFAlizer-for-Unity-1.0.0" and "libmysofa" were placed in the same folder level.
Then i have just followed the installation steps as provided in the README.md in the "SOFAlizer-for-Unity-1.0.0" folder.

**Comment by petibub** [comment]
OK, it seems like you've done everything right.

I finally was able to reproduce this error: for a given combination of HRTFs and changing the audio sampling rate and restarting unity engine. 

I'll need some time to figure out what the problem is and how to fix it. Sorry for the inconvenience and stay tuned.

**Comment by petibub** [comment]
I think that I've found the problem and fixed it. Could you check my last commit?

**Comment by petibub** [comment]
Version 1.0.1 fixes the problem.

**Comment by vensanmazmanyan** [comment]
Thank you.
I can confirm, it doesn't crash any more.

I am not sure if this is the correct thread for some additional observations.

When playing a scene in Unity there are some artifacts that are audible when rotating the listener rapidly.
They are always present no matter how i set my buffer sizes and even with a high resolution data set (FHK - HRIR_FULL2DEG.sofa) that has 2° spatial resolution.

Here is a short video to illustrate the issue.

[SOFAlizer_for_Unity_Test.zip](https://github.com/sofacoustics/SOFAlizer-for-Unity/files/1143816/SOFAlizer_for_Unity_Test.zip)

The data set from bank 2 is the high res SOFA.
Those clicks are not too loud, but still quite audible with rapid movements.
What could be the reason for them?

**Comment by hagenw** [comment]
I don't know how Unity or the SOFAlizer works, but those clicks are typical artefacts for rapid movements that are realized by cross-fading between different impulse responses.

**Comment by petibub** [comment]
Yeah, Hagen is right: you'll have some cross-fading effects when switching between the HRTFs. But, the switch is currently programmed in a poor way and it could be much better. Signal processing optimizations are on my to-do list. 
If you want, you could open a new ticket for that - I'd protocol the further steps there.

**Comment by vensanmazmanyan** [comment]
OK, great. 
I am really glad that this is something that can be fixed and is not a Unity limitation.

I will then create the ticket.
