### ISSUE TITLE
Feasibility of porting SOFAlizer to platforms other than Windows? 

### ISSUE THREAD

**Issue by rcoppy** [sofacoustics/SOFAlizer-for-Unity#10]
Hi there! Thanks so much for your work on this project, it's really cool :) 

I'm working for a client that needs to be able to use spatial audio / custom HRTFs in the context of web assembly applications, and I was just wondering if you had any thoughts on what first steps might be to port SOFAlizer to a platform like wasm. 

(In particular, modern web browsers have access to something called the Web Audio API, which can be used for [background audio processing](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_AudioWorklet)). 

I'm happy to do the work, but don't quite know where to start. 

Thanks for your time! -Alex

**Comment by petibub** [comment]
Dear rcoppy, 

that's a nice idea. Would like to follow it. 

The first step would be to implement a SOFA loader. The main challenge would be to have access to a HDF loader (the binary container of SOFA). I don't know the details of Wasm, it might be just available, or you could integrate the C-based loader from https://github.com/hoene/libmysofa. For a general overview, you could also have a look at how WebSOFA implemented the loader: https://github.com/CWBudde/WebSofa. 
Then, the next step would be to implement the convolution. I had a look at the example from Wasm and I guess that the background audio processing might work, indeed. 

If you need further assistance, plz PM me. 

For further reading on Web APIs, this interesting survey might help as well: https://gala.gre.ac.uk/id/eprint/35842/7/35842_McARTHUR_A_survey_of_3D_audio.pdf

**Comment by rcoppy** [comment]
Thanks so much, I really appreciate the pointers! :)

**Comment by rcoppy** [comment]
Hello! I know it's been an incredibly long time, but I did finally get around to trying to port MySOFA. I can load it into browser without crashing, but as of yet it's unable to successfully load any HRTFs. 

Here is a prerelease with my progress so far: https://github.com/rcoppy/libmysofa-wasm/releases/tag/sofa-wasm-0.0.1

Thank you again for pointing me in the direction of MySOFA to begin with! Cheers, Alex
