### ISSUE TITLE
Audible artifacts during rapid head movements

### ISSUE THREAD

**Issue by vensanmazmanyan** [sofacoustics/SOFAlizer-for-Unity#2]
When playing a scene in Unity there are some artifacts, sounding like series of clicks, that are audible when rotating the listener rapidly. 
Possible cause is the cross-fade used when switching between two different IRs during head movement.

They are always present no matter how the buffer size is being set and even with a high resolution data set (FHK - HRIR_FULL2DEG.sofa) that has 2° spatial resolution. 
The artifacts are rather quiet when moving slowly, but get quite prominent during rapid, fast head movements.

**Comment by petibub** [comment]
The current version targets these glitches. Please check if it is better now...
