### ISSUE TITLE
mysofa.h file missing

### ISSUE THREAD

**Issue by cjenny0** [sofacoustics/SOFAlizer-for-Unity#3]
In the current SOFAlizer for Unity Releases 1.0.0 and 1.0.1 the following error occurs: „Datei (Include) kann nicht geöffnet werden „mysofa.h“: No such file or directory“. We missed adding the mysofa.h file from the libmysofa libary. Bug will be fixed in the next Release.

**Comment by vensanmazmanyan** [comment]
Hi,

i also had the issue recently, but found a workaround.
I have downloaded "libmysofa-master" from here:

https://github.com/hoene/libmysofa 

Then unzipped it into the same folder level as "SOFAlizer-for-Unity-master"
and renamed the folder as "libmysofa" . Without "-master" at the end of the folder name.
After that i was able to build the plugin on Win 10 with VS 2017 community with the SDK for Windows 10 and the extra installed build tools v140 .

**Comment by unitydeveloper02** [comment]
I tried to do as you wrote and did not work.
Could you describe in more detail what you did?

**Comment by unitydeveloper02** [comment]
hi guys, can someone help me, I can not get rid of the error "mysofa.h file is missing". Can someone give me a working version of the plug-in?

**Comment by petibub** [comment]
It's here: https://github.com/hoene/libmysofa/blob/master/src/hrtf/mysofa.h
We will add it to the SOFAlizer repository in the next release...

**Comment by vensanmazmanyan** [comment]
Hi, 
here is the version i have managed to compile with the additional steps:
[SOFAlizer_Win10_64bit.zip](https://github.com/sofacoustics/SOFAlizer-for-Unity/files/1474354/SOFAlizer_Win10_64bit.zip)

**Comment by unitydeveloper02** [comment]
Thank you very much.
On my computer everything works fine, but on another machine there is an error, see the screenshot below. Help me please, I installed Microsoft Visual C ++, but it did not help.
[Error Screen](https://drive.google.com/open?id=1VBNg7kPQ20ANw1pxkysAlvS6E8wtMXeg)

**Comment by petibub** [comment]
the missing files have been added - issue closed.
