### ISSUE TITLE
How to disable the level normalization of the HRTFs ?

### ISSUE THREAD

**Issue by vensanmazmanyan** [sofacoustics/SOFAlizer-for-Unity#6]
Hello,

i would like to perform some HRTF comparisons aimed at sound coloration.
Is there a way to disable the level normalization of SOFAlizer in order to maintain original loudness levels when changing the sound coloration?

**Comment by petibub** [comment]
We currently always do the normalization. If you want to the change that you could disable that in the sources and recompile. Or, you simple play your sounds louder/softer, compensating the normalization. (The normalization is a simple gain and the system is linear.)

Just a note on your experiment: when changing the sound coloration, your loudness should not change - and vice versa. In other words, you should assume that the coloration changes even for slightly different presentation levels.

**Comment by vensanmazmanyan** [comment]
Thank you for your quick response!

With "original loudness levels" I meant preserving the natural gain change, when changing the gain in an isolated frequency range in the spectrum. If that gain gets compensated by the normalization the sound coloration perception is totally different, than intended.

For example, if the treble range is dipped and the IR is normalized afterwards, the perceived sound coloration is bass boost and not trebble dip. I need to avoid that and thanks to your answer I now know how.
