### ISSUE TITLE
Crash when using multiple sound sources.

### ISSUE THREAD

**Issue by Flichtshooter** [sofacoustics/SOFAlizer-for-Unity#7]
hello,

I'm trying to use this plugin for a project and would like to use multiple (moving) sound sources. but when i try to do so unity crashes (without a report) as soon as the second sound source is instanced(with spatializer user params or with spatialize turned on). i tried multiple setups to no avail so far.so i'm wondering if i'm doing something wrong or that it simply is not supported.

**Comment by petibub** [comment]
I have never tested SOFAlizer for more than one sound source. From your report, it seems like SOFAlizer does not support multiple sound sources (no clue why, though). I have currently no time to look into that, maybe someone else has an idea...

**Comment by Flichtshooter** [comment]
Thanks for the quick response.

The unity Script looks find (steam audio(another spatializer) seems to do it in a similar way). so i'm guessing its somewhere in the plugin.i would take a look but i'm clueless when it comes to plugins or at least sound plugins.anyways i understand that you dont have time right now so i will try to get something working with a single audio source for now.

edit: this is just a guess but its has to do with the loading process of the .sofa file since every time i instance an object there is a freeze (at least in VR(get send to the loading room)). im guessing its something to do with the HRTF data being replaced while still in use.

**Comment by JesperU** [comment]
I get the same crash of Unity with multiple sound sources and the SOFAlizer plugin. Could be really nice if someone could solve this.
